Disable libdmity for now
Maybe need to link against HIDL?
device/samsung/aries-common/shims/libdmitry/libdmitry.c:148: error: undefined reference to 'android::SensorManager::SensorManager(android::String16 const&)'
device/samsung/aries-common/shims/libdmitry/libdmitry.c:165: error: undefined reference to 'android::SensorManager::createEventQueue(android::String8, int)'
device/samsung/aries-common/shims/libdmitry/libdmitry.c:205: error: undefined reference to 'android::SensorManager::~SensorManager()'